---
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
branches:
  only:
    - master
before_build:
  - nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
test_script:
  - dotnet test .\ElGamalHomoTests\ElGamalHomoTests.csproj --no-build
configuration: Release
environment:
  AppVeyorAPIToken:
    secure: GvygCCndEp8eiXvItooIyglWYnyfUvg4YNyaufw3N3A=
  AppVeyorGlobalAPIToken:
    secure: XaWtuymf7dtXgjvEdnxXZVuIGVwMYUqOcE3dl3f3JzA=
  NugetAPIToken:
    secure: U630adFlFmWqwvorvfwA+YvFtAkfL+vw1EX0vCXbyk+R6qiLkIeqKek9yK+poBjV
image: "Visual Studio 2017 Preview"
nuget:
  disable_publish_on_pr: true
version: "0.10.0.{build}"
