on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    env:
      TAG_VERSION: 0.0.0
    steps:
    - uses: actions/checkout@v2
    - name: Get the tag version
      if: startsWith(github.ref, 'refs/tags/v')
      run: echo ::set-env name=VERSION::${GITHUB_REF#refs/tags/v}
    - name: Setup nuget
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore packages
      run: nuget restore
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
    - name: Build with msbuild
      run: msbuild -p:Configuration=Release -p:Version=$TAG_VERSION
    - name: Run tests
      run: dotnet test --configuration Release --no-build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build-artifacts
        path: .

  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v1
      with:
        name: build-artifacts
        path: .
    - name: Pack nuget packages
      run: dotnet pack --configuration Release --include-symbols --no-build
    # - name: Publish nuget packages
    #   run: dotnet nuget push **/*.nupkg --api-key ${{ github.token }} --source "github"
