on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Version patching
    - name: Get the tag version
      if: startsWith(github.ref, 'refs/tags/v')
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}
    - name: Patch Directory.Build.props and .csproj version
      if: steps.get_version.outputs.VERSION
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "<Version>.*</Version>"
        replace: format('{0}{1}{2}', "<Version>", ${{ steps.get_version.outputs.VERSION }}, "</Version>")
        include: "Directory\\.Build\\.props|.*\\.csproj"

    # Build environment
    - name: Setup nuget
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore packages
      run: nuget restore
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0

    # Build
    - name: Build with msbuild
      run: msbuild -p:Configuration=Release

    # Test
    - name: Run tests
      run: dotnet test --configuration Release --no-build

    # Upload artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build-artifacts
        path: .

  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v1
      with:
        name: build-artifacts
        path: .
    - name: Pack nuget packages
      run: dotnet pack --configuration Release --include-symbols --no-build
    # - name: Publish nuget packages
    #   run: dotnet nuget push **/*.nupkg --api-key ${{ github.token }} --source "github"